language: cpp
sudo: required
dist: trusty
cache:
  ccache: true
  apt: true
  directories:
    - obj-firefox
    - obj-x86_64-pc-linux-gnu
env:
  global:
    - MAKE_ARGS=-j4
    - USE_CCACHE=true
    - MOZ_OBJDIR=obj-firefox
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - autoconf2.13
      - build-essential
      - ccache
      - gcc-4.9
      - g++-4.9
      - python-dev
      - python-pip
      - python-setuptools
      - unzip
      - uuid
      - zip
      - libasound2-dev
      - libdbus-glib-1-dev
      - libgconf2-dev
      - libgtk2.0-dev
      - libgtk-3-dev
      - libpulse-dev
      - yasm
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew install autoconf213 yasm ccache; fi
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20
jobs:
  include:
    - stage: test
      os:
        - linux
      script: skip
    - stage: ./mach build export
      script: ./mach configure && ./mach build export
    - stage: ./mach build compile
      script: ./mach configure && ./mach build compile
    - stage: ./mach build libs
      script: ./mach configure && ./mach build libs
    - stage: ./mach build tools
      script: ./mach configure && ./mach build tools
    - stage: ./mach build binaries
      script: ./mach configure && ./mach build binaries
    - stage: ./mach build install-manifests
      script: ./mach configure && ./mach build install-manifests
    - stage: ./mach build
      script: ./mach configure && ./mach build
